version: "3"

services:

  app:
    build:
      context: "./"
      dockerfile: Dockerfile
    container_name: 'kafka-consumer'
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: 192.168.178.24:9092

    ports:
      - '8082:8082'
    networks:
      - my-proxy-net
networks:
  my-proxy-net:
    external:
      name: custom_network