# Default values for kafka-consumer.
replicaCount: 1

image:
  repository: rinkuls/kafka-consumer
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort  # Changed from NodePort to ClusterIP for internal service exposure.
  port: 8082

kafka:
  bootstrapServers: "kafka-deployment.kafka-infra.svc.cluster.local:9092"
  schemaRegistryUrl: "http://my-schema-registry.kafka-infra.svc.cluster.local:8081"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
