apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-consumer.fullname" . }}
  labels:
    {{- include "kafka-consumer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-consumer.selectorLabels" . | nindent 4 }}
